#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Akito Noguchi
# SPDX-License-Identifier: BSD-3-Clause
import sys

result = 1

for line in sys.stdin:
    try:
        num = int(line)
    except:
        num = float(line)
    result *=num

print(result)
