#!/usr/bin/python3
import sys

for line in sys.stdin:
    try:
        num = int(line)
    except:
        num = float(line)
    
    print(" ")

    for m in range(1, 11):
        result = pow(num,m)
        print(result)
